language: java

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7

sudo: false

install: true

script: 
  - mvn -q -N io.takari:maven:wrapper -Dmaven=3.3.9
  - echo 'MAVEN_OPTS="-Xmx800M -XX:MaxPermSize=256M -enableassertions"' > $HOME/.mavenrc
  - set -o pipefail
  - ./mvnw -q -Dmaven.test.skip=true clean install

build_with_tests:
  - ./mvnw -q  -Dmaven.surefire.debug="-Dorg.slf4j.simpleLogger.defaultLogLevel=warn -Dorg.apache.sling.commons.log.level=WARN" clean install -DHttpTestBase.readyTimeoutSeconds=300 -PintegrationTests 2>&1 |  egrep -v "^\W*at|DEBUG|WARN|INFO|REGISTER|\*ERROR\*|^ERROR|org\.ops4j\.pax\.|^\W*- |^org\.apache\.|^registerMimeType"

notifications:
  email: false
