language: java

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7

sudo: false

install: true

script: 
  - mvn -N io.takari:maven:wrapper -Dmaven=3.3.9
  - echo 'MAVEN_OPTS="-Xmx800M -XX:MaxPermSize=256M -enableassertions"' > $HOME/.mavenrc
  - sh -x ./mvnw clean install -DHttpTestBase.readyTimeoutSeconds=300 -PintegrationTests

notifications:
  email: false
