language: java

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7

sudo: false

install: true

script:
  - mvn -q -N io.takari:maven:wrapper -Dmaven=3.3.9
  - echo 'MAVEN_OPTS="-Xmx800M -XX:MaxPermSize=256M -enableassertions"' > $HOME/.mavenrc
  - set -o pipefail
  - ./mvnw -Dmaven.test.skip=true clean install | tee >(tail -500 1>&2) | grep "Building Apache"


notifications:
  email: false
