language: java

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7

sudo: false

install: true

env:
  global:
     - MAVEN_OPTS="-Xmx512M -XX:MaxPermSize=256M -enableassertions"

script: 
  - mvn -N io.takari:maven:wrapper -Dmaven=3.3.9
  - ./mvnw -q clean install -DHttpTestBase.readyTimeoutSeconds=300 -PintegrationTests

notifications:
  email: false
